### ISSUE TITLE
why not just use "key.path"

### ISSUE THREAD

**Issue by Evertt** [vapor/path-indexable#1]
As in, why is it better to access something with `json["users", 1, "name"]` instead of with `json["users.1.name"]`, because as far as I know, you don't get compiler-time type-checking in either of those methods. And I can't think of any other possible benefit.

**Comment by loganwright** [comment]
@Evertt the benefit is largely syntax, and now that you say it, it might be worthwhile to add a `path:` subscript that uses your syntax, ie: `json["users.1.name"]`.

The biggest difference from your example is that one can only use keys, and one can access arrays and dictionaries interchangeably, for example consider the following json:

``` Json
{
    "a" : [
        {
            "b" : 2
        }
    ]
}
```

One could call `json["a", 0, "b"] // = 2`

Mostly, it was just a preference of syntax in a way to add the same key path support to multiple conforming objects. Let us know if you think the feature warrants revisiting 👍

**Comment by Evertt** [comment]
> Let us know if you think the feature warrants revisiting 👍

Nope, this seems pretty good to me. :-) Sure I wouldn't say no to the _addition_ of a `path:` subscript, but I never say no to an extra way to express things. :-)

**Comment by loganwright** [comment]
@Evertt almost forgot one other thing. I'm going to add it here just in case the thread comes up again 😄 

Occasionally Json uses keypaths as a key, for example 

```
{"user.name" : "cool-user"}
```

I'm not sure it's the best practice, but it does exist in areas we cn't control, and we need a way to support it

**Comment by tanner0101** [comment]
Supporting `"blah.blah"` as a JSON key is critical.

**Comment by Evertt** [comment]
Ah yes of course.

**Comment by Evertt** [comment]
Actually guys, I would like to reopen this issue with the following suggestion. I would personally really like to have both methods of subscripting supported, because I really see benefit in both methods for different reasons.

So then how about the case that a key literally has a period in it? I would say, prefer literal keys over keys-paths. I'll make it clear with an example. Say my JSON looks like this:

```
{
    "user.name": "Evert",
    "user": {
        "name": "Tanner"
    }
}
```

And I write `json["user.name"]` then I believe it should return "Evert" and not "Tanner", because it should prefer literal keys over key-paths. So in that case the only way to get "Tanner" would be to write `json["user", "name"]`. Does that make sense?

But let's be honest, this is an edge case that will most likely never happen. But _if_ it happens then I think the solution I now provided is a good solution. And having both subscripting options available is very valuable to me.

**Comment by tanner0101** [comment]
You can do that like `json[path: "user.name"]`

https://github.com/qutheory/path-indexable/blob/master/Sources/PathIndexable/PathIndexable%2BSubscripting.swift#L69

**Comment by Evertt** [comment]
@tannernelson to explain a little bit what attracts me to the "user.name" form, it's because of the brevity.

Writing json["post.author.name"] is just shorter than writing json["post", "author", "name"], however that advantage completely disappears when you need to preface it with `path:`. So I would prefer if that's not necessary.

**Comment by loganwright** [comment]
I think I'd prefer to keep the `path:` as an external argument to avoid ambiguity. It's a simple way to allow users to have a more concise syntax. With autocomplete, it should only be a couple of keystrokes.

I think we should keep this proposal up another week and consider some implementation details and see if others in the community have opinions they'd like to weigh in.
